name: Deploy to Staging VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Containers
        run: |
          # Use rsync to copy the latest code to deployment directory.
          # (This safely merges the new code without overwriting the .env files or certs).
          rsync -a --exclude='.git/' ./ ~/Ephemeral-PR-Environments/
          
          # Navigate to the deployment infra folder
          cd ~/Ephemeral-PR-Environments/infra
          
          # Rebuild and restart the containers
          docker compose -f docker-compose.staging.yml up --build -d
    
      # Clean up old Docker images to save disk space(Temporary)
      - name: Docker Auto-Cleanup
        run: docker system prune -af